### ISSUE TITLE
name error execfile not defined 

### ISSUE THREAD

**Issue by peter-urban** [epifanio/groundtruther#6]
I tried to load the plugin into QGIS but I got the following error message:

```
NameError: name 'execfile' is not defined 
Traceback (most recent call last):
  File "/home/peurban/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/groundtruther/dependencies/solver.py", line 11, in SolveDependencies
    import pip
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/peurban/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/groundtruther/__init__.py", line 35, in classFactory
    from .groundtruther import GroundTruther
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/peurban/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/groundtruther/groundtruther.py", line 35, in 
    from groundtruther.dependencies.solver import SolveDependencies
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/peurban/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/groundtruther/dependencies/solver.py", line 5, in 
    class SolveDependencies():
  File "/home/peurban/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/groundtruther/dependencies/solver.py", line 13, in SolveDependencies
    execfile(os.path.join(self.pip_dir, 'get_pip.py'))
NameError: name 'execfile' is not defined


Python version: 3.10.13 (main, Nov 10 2011, 15:00:00) [GCC 12.2.0] 
QGIS version: 3.32.3-Lima Lima, exported 

Python Path:
/app/share/qgis/python
/home/peurban/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/peurban/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/app/lib/python3.10/site-packages
/usr/lib/python3.10/site-packages
/home/peurban/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
```

Is this a problem with the python version I am using? Cause I googled the error and found that execfile seems to have been removed in python 3:
I googled the error and found: https://stackoverflow.com/questions/436198/what-is-an-alternative-to-execfile-in-python-3

**Comment by peter-urban** [comment]
I investigated further: the issue seems to be with solver.py
I fixed two issues with solver.py, but executing get_pip.py does not do anything on my system. 

It is likely that this is an issue with the flatpak version of qgis (which I am using), where pip is apparently not installed by default.

**Comment by peter-urban** [comment]
Ok, I gave up on the flatpak version, solver.py works fine now if QGIS is install via e.g. anaconda

**Comment by peter-urban** [comment]
fixed with https://github.com/epifanio/groundtruther/pull/7
